# Generated by Django 5.1.7 on 2025-03-18 16:37

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="codigos",
            fields=[
                (
                    "id_proyecto",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("codigo", models.CharField(max_length=100)),
                ("activo", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
