# Generated by Django 5.1.7 on 2025-03-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrador", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="codigos",
            old_name="id_proyecto",
            new_name="id_codigo",
        ),
    ]
