# Generated by Django 5.1.7 on 2025-04-17 14:19

import apps.productos.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="color",
            fields=[
                (
                    "id_color",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("uuid_color", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("cod_color", models.CharField(blank=True, max_length=10, null=True)),
                ("bandera", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="productos",
            fields=[
                (
                    "id_producto",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("uuid_producto", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("codigo", models.CharField(blank=True, max_length=8, null=True)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "precio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("bandera", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="seccion",
            fields=[
                (
                    "id_seccion",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("uuid_seccion", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("seccion", models.CharField(blank=True, max_length=50, null=True)),
                ("bandera", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="tallas",
            fields=[
                (
                    "id_tallas",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("uuid_tallas", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("talla", models.CharField(blank=True, max_length=50, null=True)),
                ("cod_talla", models.CharField(blank=True, max_length=50, null=True)),
                ("bandera", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="tipo",
            fields=[
                (
                    "id_tipo",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("uuid_tipo", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("tipo", models.CharField(blank=True, max_length=50, null=True)),
                ("bandera", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="galeria_prod",
            fields=[
                (
                    "id_galeria",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("uuid_galeria", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "imagenes",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.productos.models.galeria_prod,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fk_color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos.color",
                    ),
                ),
                (
                    "fk_productos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos.productos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="detalle_prod",
            fields=[
                (
                    "id_detalle",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("uuid_detalle", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("bandera", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fk_color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos.color",
                    ),
                ),
                (
                    "fk_productos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos.productos",
                    ),
                ),
                (
                    "fk_talla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos.tallas",
                    ),
                ),
                (
                    "fk_tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="productos.tipo"
                    ),
                ),
            ],
        ),
    ]
