# Generated by Django 5.1.7 on 2025-04-17 14:20

import apps.productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galeria_prod",
            name="imagenes",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.productos.models.galeria_prod
            ),
        ),
    ]
