# Generated by Django 5.1.7 on 2025-04-17 15:45

import apps.productos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_alter_galeria_prod_imagenes"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalle_prod",
            name="fk_seccion",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="productos.seccion",
            ),
        ),
        migrations.AlterField(
            model_name="galeria_prod",
            name="imagenes",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.productos.models.galeria_prod
            ),
        ),
    ]
