# Generated by Django 5.1.7 on 2025-04-29 22:10

import apps.productos.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_detalle_prod_fk_seccion_alter_galeria_prod_imagenes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galeria_prod",
            name="imagenes",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.productos.models.galeria_prod
            ),
        ),
        migrations.CreateModel(
            name="inventario",
            fields=[
                (
                    "id_inventario",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "uuid_inventario",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("stock", models.BigIntegerField()),
                ("cantidad", models.BigIntegerField()),
                ("almacen", models.IntegerField()),
                ("bandera", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fk_det_productos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos.productos",
                    ),
                ),
            ],
        ),
    ]
