# Generated by Django 5.1.7 on 2025-04-29 22:24

import apps.productos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0004_alter_galeria_prod_imagenes_inventario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galeria_prod",
            name="imagenes",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.productos.models.galeria_prod
            ),
        ),
        migrations.AlterField(
            model_name="inventario",
            name="fk_det_productos",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="productos.detalle_prod"
            ),
        ),
    ]
