# Generated by Django 5.1.7 on 2025-03-11 17:04

import apps.loggin.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="estados",
            fields=[
                (
                    "id_pais",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("uuid_estados", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("estados", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="pais",
            fields=[
                (
                    "id_pais",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("uuid_pais", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("pais", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="permisos",
            fields=[
                (
                    "id_permisos",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("uuid_permisos", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("permisos", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="municipios",
            fields=[
                (
                    "id_pais",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("uuid_mun", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("municipios", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fk_estados",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loggin.estados"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="estados",
            name="fk_pais",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="loggin.pais"
            ),
        ),
        migrations.CreateModel(
            name="sesiones",
            fields=[
                (
                    "id_sesion",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("uuid_sesion", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("correo", models.EmailField(max_length=254, null=True)),
                ("usuario_sesion", models.CharField(max_length=100)),
                ("contra", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fk_permisos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loggin.permisos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="restablecer_contras",
            fields=[
                (
                    "id_restablece",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "uuid_restablece",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("contra_anterior", models.CharField(max_length=200)),
                (
                    "activa",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO")], max_length=2
                    ),
                ),
                ("bandera", models.IntegerField()),
                ("bandera2", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fk_sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loggin.sesiones",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="historial_sesiones",
            fields=[
                (
                    "id_historial",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "uuid_historial",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("fecha", models.DateField()),
                ("direccion_ip", models.GenericIPAddressField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fk_sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loggin.sesiones",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="usuarios",
            fields=[
                (
                    "id_usuarios",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("uuid_usu", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("nombre", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("fecha_nac", models.DateField()),
                (
                    "estado_civil",
                    models.CharField(
                        choices=[
                            ("soltero", "Soltero"),
                            ("casado", "Casado"),
                            ("union_libre", "Union Libre"),
                            ("viudo", "Viudo(a)"),
                            ("sin_espec", "No especificar"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino")], max_length=1
                    ),
                ),
                ("telefono", models.IntegerField()),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.loggin.models.imagenes_usuario,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fk_municipios",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loggin.municipios",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sesiones",
            name="fk_usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="loggin.usuarios"
            ),
        ),
    ]
