# Generated by Django 5.1.7 on 2025-03-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loggin", "0004_rename_id_pais_estados_id_estados"),
    ]

    operations = [
        migrations.RenameField(
            model_name="municipios",
            old_name="id_pais",
            new_name="id_municipios",
        ),
    ]
