# Generated by Django 5.1.7 on 2025-03-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loggin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuarios",
            name="sexo",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Femenino"), ("N", "No Definir")],
                max_length=1,
            ),
        ),
    ]
