# Generated by Django 5.1.7 on 2025-03-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loggin", "0003_usuarios_fk_cod_postal_alter_usuarios_fk_municipios"),
    ]

    operations = [
        migrations.RenameField(
            model_name="estados",
            old_name="id_pais",
            new_name="id_estados",
        ),
    ]
