# Generated by Django 5.1.7 on 2025-03-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loggin", "0005_rename_id_pais_municipios_id_municipios"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuarios",
            name="telefono",
            field=models.BigIntegerField(),
        ),
    ]
