# Generated by Django 5.1.7 on 2025-03-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loggin", "0006_alter_usuarios_telefono"),
    ]

    operations = [
        migrations.AddField(
            model_name="historial_sesiones",
            name="nombre_equipo",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
