# Generated by Django 5.1.7 on 2025-03-20 14:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loggin", "0007_historial_sesiones_nombre_equipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="datos_api_cp",
            fields=[
                (
                    "id_datos_cp",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("uuid_datos_cp", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("codigo_postal_api", models.BigIntegerField()),
                ("estado_api", models.CharField(max_length=200)),
                ("municipio_api", models.CharField(max_length=200)),
                ("colonia_api", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fk_cod_postal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loggin.usuarios",
                    ),
                ),
            ],
        ),
    ]
